/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.glb 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const desk = useGLTF('/Setup.glb')
  return(<mesh>
    <hemisphereLight intensity={0.15} groundColor="black" />
    <pointLight intensity={1} />
    
    <primitive object={desk.scene} scale={0.75} position={[0,0,-1]}rotation={[0.1,0,0]}/>
  </mesh>)
}

useGLTF.preload('/Setup.glb')
